/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package articulatesdk;

import articulatesdk.components.HeaderOneComponent;
import articulatesdk.components.SubTitleComponent;
import articulatesdk.components.VerticalTableComponent;

import java.util.List;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public ArticulateTemplate testMethod() {
        ArticulateTemplateBuilder builder = new ArticulateTemplateBuilder("1.0.0", new PageConfiguration());

        builder.addComponent(new HeaderOneComponent("Header Text One", "", "imageCaption", "alt text", "Sub Header Text", "Para text", "News"));
        builder.addComponent(new SubTitleComponent("Sub Title Yo..."));

        VerticalTableComponent table = new VerticalTableComponent(List.of("Header 1", "Header 2", "Header 3", "Header 4", "Header 5"));
        table.addRow(List.of("Value 1", "Value 2", "Value 3", "Value 4", "Value 5"));
        table.addRow(List.of("Value 1", "Value 2", "Value 3", "Value 4", "Value 5"));
        table.addRow(List.of("Value 1", "Value 2", "Value 3", "Value 4", "Value 5"));
        table.addRow(List.of("Value 1", "Value 2", "Value 3", "Value 4", "Value 5"));
        builder.addComponent(table);

        return builder.build();
    }
}
