/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package articulatesdk;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }

    @Test void test() {
        Library classUnderTest = new Library();
        String result = classUnderTest.testMethod().getRenderedTemplateString();
        System.out.println(result);
    }
}
